extends: 
  - stylelint-config-sass-guidelines
  - stylelint-config-idiomatic-order
rules:
  color-hex-case: lower
  max-nesting-depth: 5
  order/properties-alphabetical-order: null
  scss/at-extend-no-missing-placeholder: null
  selector-no-qualifying-type:
    - true
    - ignore:
      - attribute
      - class
      - id
  selector-class-pattern: '^(?:(?:o|c|u|t|s|is|has|_|js|qa)-)?[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*(?:__[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:--[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:\\[.+\\])?$'
    