version: '3.4'

services:

  client:
    container_name: fable_client
    stdin_open: true
    build: 
      context: ./client
      target: dev
    depends_on:
      - server
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
    ports:
      - 3000:3000
    environment:
      CHOKIDAR_USEPOLLING: 'true'

  server:
    container_name: fable_server
    stdin_open: true
    build: 
      context: ./server
      target: dev
    depends_on:
      - database
      - redis
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules
    ports:
      - 5000:5000
    environment:
      CHOKIDAR_USEPOLLING: 'true'
  
  database:
    image: mongo:latest
    container_name: fable_database
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=fable

  redis:
    image: redis:latest
    container_name: fable_redis
    volumes:
      - redis-data:/data/redis
    expose:
      - '6379'
    ports:
      - 6379:6379

volumes:
  mongo-data:
  redis-data: