version: '3.4'

services:
  client:
    container_name: fable_client
    stdin_open: true
    depends_on:
      - server
    build: 
      context: ./client
      target: dev
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules/
    ports:
      - '3000:3000'
    environment:
      CHOKIDAR_USEPOLLING: 'true'

  server:
    container_name: fable_server
    stdin_open: true
    build: 
      context: ./server
      target: dev
    env_file:
      - .env
    depends_on:
      - database
      - redis
    volumes:
      - ./server:/usr/src/app/server
      - ./config:/usr/src/app/config
      - /usr/src/app/server/node_modules/
    ports:
      - '5000:5000'
    environment:
      CHOKIDAR_USEPOLLING: 'true'
  
  database:
    container_name: fable_database
    image: mongo
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'

  redis:
    container_name: fable_redis
    build: ./config/redis
    ports:
      - '6378:6378'

volumes:
  mongo-data: