version: '3.4'

services:
  client:
    container_name: fable_client
    stdin_open: true
    depends_on:
      - server
    build: 
      context: ./client
      target: dev
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
    ports:
      - '3000:3000'
    environment:
      CHOKIDAR_USEPOLLING: 'true'

  server:
    container_name: fable_server
    stdin_open: true
    build: 
      context: ./server
      target: dev
    depends_on:
      - database
      - redis
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules
    ports:
      - '5000:5000'
    environment:
      CHOKIDAR_USEPOLLING: 'true'
  
  database:
    container_name: fable_database
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=fable
    volumes:
      - mongo-data:/data/db

  redis:
    container_name: fable_redis
    build: ./config/redis
    ports:
      - '6379:6379'

volumes:
  mongo-data: