version: '3.4'

services:

  nginx:
    container_name: fable_nginx
    build: ./config/nginx
    depends_on:
      - client
      - server
    volumes:
      - ./client/build:/var/www/public
    ports:
      - '80:80'
  
  client:
    stdin_open: false
    build: 
      context: ./client
      target: prod
    environment:
      CHOKIDAR_USEPOLLING: 'false'

  server:
    stdin_open: false
    build: 
      context: ./server
      target: prod
    environment:
      CHOKIDAR_USEPOLLING: 'false'