enum ActionTypes {
  ADD_MESSAGE = 'ADD_MESSAGE',
  REMOVE_MESSAGE = 'REMOVE_MESSAGE',
  UPDATE_USER = 'UPDATE_USER',
  SAVE_STORY = 'SAVE_STORY',
  UPDATE_THEME = 'UPDATE_THEME',
  SET_TOKEN = 'SET_TOKEN',
  REMOVE_TOKEN = 'REMOVE_TOKEN',
}

export default ActionTypes;
