enum ActionTypes {
  MESSAGE_ADD = 'MESSAGE_ADD',
  MESSAGE_REMOVE = 'MESSAGE_REMOVE',
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_UPDATE = 'USER_UPDATE',
  STORY_SAVE = 'STORY_SAVE',
}

export default ActionTypes;
